(()=>{"use strict";
const NS=window.SignWellOriginHero=window.SignWellOriginHero||{};let state=null;
const VS=`attribute vec2 a;void main(){gl_Position=vec4(a,0.,1.);}`;
const FS=`precision highp float;uniform vec2 r;uniform float t;uniform vec2 m;uniform float dark;
float sdTorus(vec3 p,vec2 q){vec2 x=vec2(length(p.xz)-q.x,p.y);return length(x)-q.y;}
mat2 R(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);}float map(vec3 p){p.xy*=R(.18*sin(t*.35));p.xz*=R(t*.13+m.x*.28);p.yz*=R(-.45+m.y*.18);return sdTorus(p,vec2(1.0,.28));}
vec3 norm(vec3 p){vec2 e=vec2(.002,0.);return normalize(vec3(map(p+e.xyy)-map(p-e.xyy),map(p+e.yxy)-map(p-e.yxy),map(p+e.yyx)-map(p-e.yyx)));}
void main(){vec2 uv=(gl_FragCoord.xy-.5*r)/r.y;vec3 ro=vec3(0.,0.,3.8),rd=normalize(vec3(uv,-1.7));float d=0.,h=0.;bool hit=false;for(int i=0;i<72;i++){vec3 p=ro+rd*d;h=map(p);if(abs(h)<.0015){hit=true;break;}d+=h*.78;if(d>7.)break;}if(!hit){gl_FragColor=vec4(0.);return;}vec3 p=ro+rd*d,n=norm(p);float fr=pow(1.-max(dot(n,-rd),0.),3.);vec3 L=normalize(vec3(-.5,.8,.7));float hi=pow(max(dot(reflect(-L,n),-rd),0.),24.);float band=.5+.5*sin((p.x+p.y*1.3)*8.+t*.4);vec3 camel=vec3(.72,.58,.39),blue=vec3(.47,.65,.72),green=vec3(.18,.31,.29),cream=vec3(.94,.91,.84);vec3 col=mix(cream,blue,.28+band*.16);col=mix(col,camel,.12);col=mix(col,green,fr*.42);col+=hi*.72;col+=fr*.28;if(dark>.5)col=mix(col,vec3(.16,.25,.24),.42)+hi*.25;float a=.36+fr*.5+hi*.18;gl_FragColor=vec4(col,a);}`;
function shader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);return gl.getShaderParameter(s,gl.COMPILE_STATUS)?s:null}
function mount(){const c=document.querySelector('[data-sw-origin-canvas]');if(!c||c.dataset.ready==='1')return;c.dataset.ready='1';const gl=c.getContext('webgl',{alpha:true,antialias:false,premultipliedAlpha:true});if(!gl)return;const v=shader(gl,gl.VERTEX_SHADER,VS),f=shader(gl,gl.FRAGMENT_SHADER,FS);if(!v||!f)return;const p=gl.createProgram();gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))return;gl.useProgram(p);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const a=gl.getAttribLocation(p,'a');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);const ur=gl.getUniformLocation(p,'r'),ut=gl.getUniformLocation(p,'t'),um=gl.getUniformLocation(p,'m'),ud=gl.getUniformLocation(p,'dark');let mx=0,my=0,tx=0,ty=0,raf=0,last=0,visible=true;const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
function resize(){const d=Math.min(devicePixelRatio||1,innerWidth<760?1.35:1.75),w=Math.max(1,Math.round(c.clientWidth*d)),h=Math.max(1,Math.round(c.clientHeight*d));if(c.width!==w||c.height!==h){c.width=w;c.height=h;gl.viewport(0,0,w,h)}}
function move(e){const q=c.getBoundingClientRect();tx=((e.clientX-q.left)/q.width-.5)*2;ty=((e.clientY-q.top)/q.height-.5)*-2}function leave(){tx=ty=0}c.addEventListener('pointermove',move,{passive:true});c.addEventListener('pointerleave',leave,{passive:true});const io=new IntersectionObserver(x=>visible=x[0]?.isIntersecting!==false,{threshold:.01});io.observe(c);
function draw(n){raf=requestAnimationFrame(draw);if(!visible)return;if(reduce&&n-last<180)return;last=n;resize();mx+=(tx-mx)*.045;my+=(ty-my)*.045;gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.uniform2f(ur,c.width,c.height);gl.uniform1f(ut,n*.001);gl.uniform2f(um,mx,my);const dark=document.documentElement.dataset.theme==='dark'||document.body.classList.contains('dark')||matchMedia('(prefers-color-scheme: dark)').matches;gl.uniform1f(ud,dark?1:0);gl.drawArrays(gl.TRIANGLES,0,3)}raf=requestAnimationFrame(draw);state={c,gl,raf,io};}
NS.mount=mount;new MutationObserver(()=>{if(document.querySelector('[data-sw-origin-canvas]:not([data-ready="1"])'))mount()}).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});if(document.readyState!=='loading')mount();else addEventListener('DOMContentLoaded',mount,{once:true});})();